server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://43.143.165.110:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: liuqiang
    hikari:
      connection-test-query: SELECT 1 # 自动检测连接
      connection-timeout: 60000 #数据库连接超时时间,默认30秒
      idle-timeout: 500000 #空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 540000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      maximum-pool-size: 12 #连接池最大连接数，默认是10
      minimum-idle: 10 #最小空闲连接数量
      pool-name: SPHHikariPool # 连接池名称
  data:
    redis:
      host: 43.143.165.110
      port: 6379



#  servlet:
#    max-request-size: 100MB
#    max-file-size: 10MB

# 用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full



# 属性类配置
# minio相关属性
ltb:
  minio:
      endpoint: http://43.143.165.110:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket-name: lease


# 日志配置
logging.level.root: info

# 拦截路径配置
web:
  admin:
    exclude-path: /admin/login/**, /doc.html
    include-path: /admin/**